### ISSUE TITLE
Read/Write Global variables

### ISSUE THREAD

**Issue by Mahmoussam** [ColinTheShark/Pyrogram-Snippets#4]
How to read/save to global variables from inside on_message handler?!
as far as i know ,telegram python API has ```context.user_data['Var']=val```

**Comment by ColinShark** [comment]
Basic python.
Define your variable outside a handler, then use `global my_var` inside of the handler and write to it like you normally would.

**Comment by Mahmoussam** [comment]
@ColinTheShark  yes i found out that ,lol .
thanks anyway
