### ISSUE TITLE
400 Bad Request in nekobin.py

### ISSUE THREAD

**Issue by lmjaedentai** [ColinTheShark/Pyrogram-Snippets#6]
```py
URL = "nekobin.com"
post = "https://nekobin.com/api/documents"

paste = requests.post(post, data={"content": text})
paste.raise_for_status()
```
output:
```py
400 Client Error: Bad Request for url: https://nekobin.com/api/documents
```
Is nekobin API not function anymore?
- https://github.com/nekobin/nekobin/pull/6#issuecomment-1135310369

**Comment by ColinShark** [comment]
Hey there, thanks for raising the issue, but I don't plan to fix anything. These Snippets were an idea for working examples, but I've not updated these (or cared about them) for a long time.

Either troubleshoot this yourself, or ask someone more interested to help out.
